# # Generated by Django 3.1.3 on 2020-11-30 18:28
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('scraping', '0003_url'),
#     ]
#
#     operations = [
#         migrations.AlterModelOptions(
#             name='vacancy',
#             options={'ordering': ['-timestamp'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
#         ),
#     ]
